---
- name: Download GeoNames data
  get_url:
    url: "{{ item.url }}"
    dest: "{{ INSTALL_DIR }}/geodata/{{ item.filename }}"
  with_items:
    - { url: "https://download.geonames.org/export/dump/admin1CodesASCII.txt", filename: "admin1CodesASCII.txt" }
    - { url: "https://download.geonames.org/export/dump/admin2Codes.txt", filename: "admin2Codes.txt" }
    - { url: "https://download.geonames.org/export/dump/cities500.zip", filename: "cities500.zip" }
    - { url: "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/v5.1.2/geojson/ne_10m_admin_0_countries.geojson", filename: "ne_10m_admin_0_countries.geojson" }
  creates:
    - "{{ INSTALL_DIR }}/geodata/admin1CodesASCII.txt"
    - "{{ INSTALL_DIR }}/geodata/admin2Codes.txt"
    - "{{ INSTALL_DIR }}/geodata/cities500.zip"
    - "{{ INSTALL_DIR }}/geodata/ne_10m_admin_0_countries.geojson"

- name: Unzip cities500.zip
  ansible.builtin.unarchive:
    src: "{{ INSTALL_DIR }}/geodata/cities500.zip"
    dest: "{{ INSTALL_DIR }}/geodata/"
    remote_src: true
  when: ansible_facts['distribution'] != 'Ubuntu'
