name: Ansible Lint
on:
  push:
    branches:
      - main

jobs:
  Immich-Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install ansbile
      - name: Install Ansible
        run: |
          python3 -m venv /workspace/will/venv
          source /workspace/will/venv/bin/activate
          python3 -m pip install ansible
          python3 -m pip install ansible-lint             

      - name: Run ansible-lint
        run: |
          ansible-lint -c ./.ansible-lint.yml ansible/playbook.*.yaml